modLoader="javafml"
loaderVersion="[31,)" #forge version dep
issueTrackerURL="https://github.com/iChun/Attachable-Grinder/issues"

[[mods]]
    modId="attachablegrinder"
    version="${file.jarVersion}" #mandatory
    displayName="Attachable Grinder"
    displayURL="https://ichun.me/mods/attachable-grinder/"
    authors="iChun"
    description='''
    Add an attachable Grinder which works on certain mobs.
    '''

[[dependencies.attachablegrinder]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.attachablegrinder]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2,1.16)"
    ordering="NONE"
    side="BOTH"
