modLoader="javafml"
loaderVersion="[34,)" #forge version dep
license="GNU Lesser General Public License v3.0"
issueTrackerURL="https://github.com/iChun/Attachable-Grinder/issues"

[[mods]]
    modId="attachablegrinder"
    version="${file.jarVersion}" #mandatory
    displayName="Attachable Grinder"
    displayURL="https://ichun.me/mods/attachable-grinder/"
    authors="iChun"
    description='''
    Add an attachable Grinder which works on certain mobs.
    '''

[[dependencies.attachablegrinder]]
    modId="ichunutil"
    mandatory=true
    versionRange="[10.0.0,11)"
    ordering="NONE"
    side="BOTH"
